### ISSUE TITLE
Mesa-git removed features this relies on

### ISSUE THREAD

**Issue by Quackdoc** [catacombing/kumo#3]
It came across as well when I thought I would test it. I reported this upstream since technically it is a regression, however heads up that Mesa git has removed this.

you use https://gitlab.freedesktop.org/mesa/mesa/-/commit/a3418105b9169b8f72745c9901db37cd545ac583

reported as a regression here
https://gitlab.freedesktop.org/mesa/mesa/-/issues/10964

PS. can't wait to test this some more :D

**Comment by chrisduerr** [comment]
This was reverted in mesa. WPE WebKit is working on a solution that doesn't require its embedded compositor anymore.
